version: "3"
services:
  ksbot:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "cqhttp"

  cqhttp:
    image: richardchien/cqhttp:latest
    env_file: .env
    environment:
      - VNC_PASSWD=${VNC_PWD}
      - COOLQ_ACCOUNT=${QQ_ACCOUNT}
      - COOLQ_URL=${COOLQ_VERSION_URL}
      - CQHTTP_USE_HTTP=true
      - CQHTTP_SERVE_DATA_FILES=true
      - CQHTTP_SHOW_LOG_CONSOLE=true
      - CQHTTP_LOG_LEVEL=info
      - FORCE_ENV=true
      - CQHTTP_POST_URL=${CQHTTP_POST_URL}
      - CQHTTP_SECRET=${COOLQ_SECRET}
      - CQHTTP_ACCESS_TOKEN=${COOLQ_TOKEN}
    volumes:
      - ./cqhttp:/home/user/coolq
    ports:
      - "9000:9000"
      - "5700:5700"
    networks:
      - bot_net

networks:
  bot_net:
    driver: bridge
  